branch-defaults:
  default:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
  django-env2:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
